export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILD = "GET_PRODUCTS_FAILD"

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAILD = "GET_PRODUCT_DETAILS_FAILD"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILD = "CREATE_PRODUCT_FAILD"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILD = "UPDATE_PRODUCT_FAILD"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILD = "DELETE_PRODUCT_FAILD"

export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const SEARCH_PRODUCTS_FAILD = "SEARCH_PRODUCTS_FAILD"

export const FILTER_PRODUCTS_REQUEST = "FILTER_PRODUCTS_REQUEST"
export const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS"
export const FILTER_PRODUCTS_FAILD = "FILTER_PRODUCTS_FAILD"
 
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST"
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS"
export const GET_PRODUCTS_BY_CATEGORY_FAILD = "GET_PRODUCTS_BY_CATEGORY_FAILD"