export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAILD = "SEND_MESSAGE_FAILD"

export const GET_CHAT_HISTORY_REQUEST = "GET_CHAT_HISTORY_REQUEST"
export const GET_CHAT_HISTORY_SUCCESS = "GET_CHAT_HISTORY_SUCCESS"
export const GET_CHAT_HISTORY_FAILD = "GET_CHAT_HISTORY_FAILD"

export const CLEAR_CHAT = "CLEAR_CHAT"