export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST"
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS"
export const GET_REVIEWS_FAILD = "GET_REVIEWS_FAILD"

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST"
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAILD = "ADD_REVIEW_FAILD"

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST"
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS"
export const UPDATE_REVIEW_FAILD = "UPDATE_REVIEW_FAILD"

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_FAILD = "DELETE_REVIEW_FAILD"