export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILD = "GET_CART_FAILD"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILD = "ADD_TO_CART_FAILD"

export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAILD = "UPDATE_CART_ITEM_FAILD"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILD = "REMOVE_FROM_CART_FAILD"

export const CLEAR_CART = "CLEAR_CART"