export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST"
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS"
export const CREATE_PAYMENT_FAILD = "CREATE_PAYMENT_FAILD"

export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST"
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS"
export const VERIFY_PAYMENT_FAILD = "VERIFY_PAYMENT_FAILD"

export const GET_PAYMENT_DETAILS_REQUEST = "GET_PAYMENT_DETAILS_REQUEST"
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS"
export const GET_PAYMENT_DETAILS_FAILD = "GET_PAYMENT_DETAILS_FAILD"