export const GET_RATINGS_REQUEST = "GET_RATINGS_REQUEST"
export const GET_RATINGS_SUCCESS = "GET_RATINGS_SUCCESS"
export const GET_RATINGS_FAILD = "GET_RATINGS_FAILD"

export const ADD_RATING_REQUEST = "ADD_RATING_REQUEST"
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS"
export const ADD_RATING_FAILD = "ADD_RATING_FAILD"

export const UPDATE_RATING_REQUEST = "UPDATE_RATING_REQUEST"
export const UPDATE_RATING_SUCCESS = "UPDATE_RATING_SUCCESS"
export const UPDATE_RATING_FAILD = "UPDATE_RATING_FAILD"

export const DELETE_RATING_REQUEST = "DELETE_RATING_REQUEST"
export const DELETE_RATING_SUCCESS = "DELETE_RATING_SUCCESS"
export const DELETE_RATING_FAILD = "DELETE_RATING_FAILD"